export const UPDATE_INGREDIENT_AMOUNT = "UPDATE_INGREDIENT_AMOUNT";
export const UPDATE_CHECKOUT_FORM = "UPDATE_CHECKOUT_FORM";
export const RESET_BURGER_STATE = "RESET_BURGER_STATE";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";

export const SAVE_ORDER = "SAVE_ORDER";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_FAILED_MESSAGE = "AUTH_FAILED_MESSAGE";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
